Fix/node16 compatible
javierbrea/cypress-localstorage-commands pull request #302
Opened 2021-04-28 09:24 UTC by kvalium

Add Node 16 in the Node engine compatibility list (see issue https://github.com/javierbrea/cypress-localstorage-commands/issues/301)

2021-04-28 16:45 UTC, javierbrea requested changes
The new node.js version should be added also to the `jobs.test.strategy.matrix.node` array on the `.github/workflows/build.yml` file in order to run tests also with this node version.

2021-04-28 16:47 UTC, javierbrea commented
Hi @kvalium @JMYfromADS,
Thanks for the PR! 🙂  I have requested a change for checking the compatibility with the new node version in the build pipeline.

2021-04-28 19:13 UTC, kvalium commented
Hello @javierbrea i've just pushed the change you had requested!

2021-04-29 05:06 UTC, javierbrea approved these changes

2021-04-29 05:21 UTC, merged